version: '3.9'

services:
  db:
    container_name: db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=USER1qwerty
      - MSSQL_PID=Developer
      - MSSQL_TCP_PORT=1433
    networks:
      - emercomTest

  app:
    container_name: app
    image: asil88/emercomapp:v1
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
    depends_on:
      - db
    networks:
      - emercomTest

networks:
  emercomTest:
    driver: bridge